### ISSUE TITLE
Focus to stay in addressbar

### ISSUE THREAD

**Issue by ev0lister** [zach-adams/simple-new-tab-url#4]
If I open a new tab the focus is in the tab, like when browsing to a new page, however, I would prefer to have the same behaviour like the original new tab page: The focus stays in the addressbar to directly start typing.

Would be a great enhancement, if possible.

**Comment by rzfzr** [comment]
I was thinking about including this in a PR....
However I found out this one does that: https://github.com/jimschubert/NewTab-Redirect

**Comment by zach-adams** [comment]
This should be added as a feature now (better late than never)
