### ISSUE TITLE
Won't open an html file on PC

### ISSUE THREAD

**Issue by Joecascio2000** [zach-adams/simple-new-tab-url#5]
I have a non-hosted html file that I use for quick access to specific links. This file is stored on my PC.

Example: 'file:///Z:/Links/Public/links.html'

I have a bookmark with this page and set at the page to open on start up with no issue. I did want to set this as the 'new tab' page and found your extension. It doesn't seem to work with local files. Can this be changed?

**Comment by uduman** [comment]
From the extension's page on the chrome store:

> Note: If your new tab url is a local file (i.e. it starts with "file://" rather than "http://") then you will have to enable the "Allow access to file URLs" permission for this extension on the Manage Extensions page.

**Comment by Joecascio2000** [comment]
> From the extension's page on the chrome store:
> 
> > Note: If your new tab url is a local file (i.e. it starts with "file://" rather than "http://") then you will have to enable the "Allow access to file URLs" permission for this extension on the Manage Extensions page.

Ah, this works. Thanks.
