### ISSUE TITLE
Won't work using "chrome://new-tab-page"

### ISSUE THREAD

**Issue by Matthew-MBG** [zach-adams/simple-new-tab-url#6]
So, I downloaded this plugin and used it in avast secure browser. Now it works fine, until I try to set the new tab page to `chrome://new-tab-page`. When I did this, it just opens a blank new tab page.

**Comment by zach-adams** [comment]
I don't have much time to deal with issues from unique Chromium-based browsers except Edge and maybe Brave.
All I can say is that Avast may have blanked out Chrome's built-in new tab page, and to use a different URL for your new tabs or move away from Avast to something like Brave.

**Comment by Matthew-MBG** [comment]
It's been 2 years, you can forget about this issue - I no longer use Avast.
