### ISSUE TITLE
Doesnt work on Edge adds garbage to URL

### ISSUE THREAD

**Issue by marcusobrien** [zach-adams/simple-new-tab-url#7]
I added www.duckduckgo.com, now when I open a new tab the url for the page is set to 

extension://oeibmbobgpgnbnlbaffdgebpeepfbnhi/duckduckgo.com

**Comment by MofoMojo** [comment]
I ran into a similar problem. Don't just use www.whatever.com... specify the protocol handler too, i.e. https://www.whatever.com

**Comment by marcusobrien** [comment]
@MofoMojo Working now, thanks for the great advice ! At last no more Bing on my new tabs !

**Comment by zach-adams** [comment]
Closing as this is related to #9
